### ISSUE TITLE
Link in README is 404

### ISSUE THREAD

**Issue by wilbowma** [aa755/SquiggleEq#1]
Upon clicking the link in the README, I get:

```
Page not found
The requested page "/vladimir/files/Anand_ICMS2016.pdf" could not be found.
```

**Comment by aa755** [comment]
The link works for me.
In any case, you can try another link:
http://www.cs.cornell.edu/~aa755/ICMS2016.pdf
If this link also doesn't work, please send me an email I will be happy to reply back with the slides.
Section 2.2 of the following tech report should also be helpful in understanding this library
http://www.nuprl.org/html/verification/verification.pdf
Also, feel free to to ask me any question.

**Comment by wilbowma** [comment]
Ah. That one works.

When I try `www.math.ias.edu/vladimir/files/Anand_ICMS2016.pdf`I get a file not found page in Firefox, but I get 403 Forbidden in via wget and curl.

**Comment by wilbowma** [comment]
Figured out this issue: https everywhere was redirecting me, and the https URL doesn't exist.
