### ISSUE TITLE
Release for coq 8.7

### ISSUE THREAD

**Issue by mattam82** [aa755/SquiggleEq#3]
Can you make a release? I'll submit an appropriate opam package afterwards.

**Comment by aa755** [comment]
Done. https://github.com/aa755/SquiggleEq/releases/tag/v1.0.3
`coq-ext-lib` is needed. But my opam could not find a version of `coq-ext-lib` that works with Coq 8.7.1.
For testing this release, I manually built `coq-ext-lib` from its [v8.7 branch](https://github.com/coq-ext-lib/coq-ext-lib/tree/v8.7)

**Comment by mattam82** [comment]
Really? Did you opam update? It worked for me this morning (maybe with 8.7.0 though)

**Comment by aa755** [comment]
[abhishek@brixpro public]$ opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[coq-core-dev] synchronized from https://coq.inria.fr/opam/core-dev
[coq-released] synchronized from https://coq.inria.fr/opam/released
[coq-extra-dev] synchronized from https://coq.inria.fr/opam/extra-dev
[default] synchronized from https://opam.ocaml.org

Updates available for coq87, apply them with 'opam upgrade':
===== ↗  1 =====
[abhishek@brixpro public]$ opam install coq-ext-lib
The following actions will be performed:
  ↘  downgrade coq         8.7.1 to 8.5.dev   [required by coq-ext-lib]
  ∗  install   coq-ext-lib 8.5.dev         
===== ∗  1   ↘  1 =====

**Comment by mattam82** [comment]
Ok, I'll fix that first then

**Comment by mattam82** [comment]
That's strange, I do have coq 8.7.1 and coq-ext-lib 0.9.7 installed with it, the version constraints on it are coq >= "8.7" < "8.8". My coq is pinned to 8.7.1 though (opam pin add coq 8.7.1). Can you try an opam install coq-ext-lib.0.9.7?

**Comment by aa755** [comment]
Yes `opam install coq-ext-lib.0.9.7` works. Maybe something is broken just on my machine.

**Comment by aa755** [comment]
I had not pinned Coq to 8.7.1
